<h1>First Look Data with Pandas</h1>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWkCG5kkVQwhKLSO8V_FR3YMBRUuflaPRaFiFnMQHI6pjyiKhLjwdKuSU&s=10" width="200" height="200">

In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
df=pd.read_csv(r'C:\Users\Dell\Python_4th_Sem\numpyand pandas\pandas_intro_practice_500_rows.csv')

In [3]:
df.head()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
0,35,Sneha,33.0,Butwal,HR,115111.0,Headphones,9,3.0,2018
1,183,Aayush,37.0,Bhaktapur,IT,28396.0,Keyboard,8,3.1,2019
2,86,Neha,32.0,Chitwan,IT,96376.0,Mouse,3,4.6,2020
3,274,Sabin,21.0,Dharan,Operations,52479.0,Webcam,5,4.3,2019
4,37,Maya,55.0,Kathmandu,IT,34862.0,Keyboard,9,1.1,2023

In [4]:
df.tail()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
495,114,Nisha,28.0,Butwal,Marketing,90771.0,Headphones,3,2.0,2025
496,97,Riya,35.0,Dharan,Marketing,$43958,Tablet,4,4.7,2020
497,226,Raj,34.0,Bhaktapur,HR,87676.0,Keyboard,8,4.0,2023
498,215,Riya,33.0,Bhaktapur,Marketing,60537.0,Headphones,3,1.4,2021
499,58,Suman,46.0,Kathmandu,HR,134168.0,Tablet,7,4.6,2018

In [5]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'City', 'Department', 'Salary', 'Product',
       'Quantity', 'Rating', 'Joining_Year'],
      dtype='str')